/**
 * A registered Home Assistant device. For more information see {@link https://developers.home-assistant.io/docs/device_registry_index}
 *
 * @public
 */
export interface HassDevice {
  /**
   * The Area which the device is placed in.
   */
  area_id: string | null;

  /**
   * A URL on which the device or service can be configured, linking to paths inside the Home Assistant UI
   * can be done by using homeassistant://<path>.
   */
  configuration_url: string | null;

  /**
   * Config entries that are linked to this device.
   */
  config_entries: string[];

  /**
   * A set of tuples of (connection_type, connection identifier). Connection types are defined in the
   * device registry module. Each item in the set uniquely defines a device entry, meaning another device
   * can't have the same connection.
   */
  connections: [connectionType: string, connectionIdentifier: string][];

  /**
   * A unix timestamp representing the time this device was first created in Home Asssitant
   */
  created_at: number;

  /**
   * Whether this device has been disabled and why
   */
  disabled_by: string | null;

  /**
   *  The type of entry. Possible values are None and DeviceEntryType enum members (only service).
   */
  entry_type: 'service' | null;
  /**
   * The hardware version of the device
   */
  hw_version: string | null;

  /**
   * Unique ID of device (generated by Home Assistant)
   */
  id: string;

  /**
   * Set of (DOMAIN, identifier) tuples. Identifiers identify the device in the outside world.
   * An example is a serial number. Each item in the set uniquely defines a device entry, meaning
   * another device can't have the same identifier.
   */
  identifiers: [domain: string, identifer: string][];

  /**
   * Labels that have been attached to the specific device
   */
  labels: string[];

  /**
   * The manufacturer of the device.
   */
  manufacturer: string | null;

  /**
   * The model name of the device.
   */
  model: string | null;

  /**
   * The model identifier of the device.
   */
  model_id: string | null;

  /**
   * A timestamp that represents the last time this device was modified in Home Assistant
   */
  modified_at: number;
  /**
   * The user configured name of the device.
   */
  name_by_user: null | string;
  /**
   * Name of this device
   */
  name: string;

  /**
   * unique identifer for the configuration entry that is the primary source of metadata for this device
   */
  primary_config_entry: string | null;

  /**
   * I don't know what the type of this one is as
   * I don't have any devices in my database that aren't null
   */
  serial_number: string | null;

  /**
   * The firmware version of the device.
   */
  sw_version: string | null;

  /**
   * Identifier of a device that routes messages between this device and Home Assistant.
   * Examples of such devices are hubs, or parent devices of a sub-device. This is used to
   * show device topology in Home Assistant.
   */
  via_device_id: string | null;
}
