/**
 * A strongly typed client for Home Assistant that uses both the HTTP and Websocket APIs
 *
 * @packageDocumentation
 */
export { initialiseHass, getConfig } from '@initialise';

export type {
  CallServiceCommand,
  CallServiceResponse,
  TriggerEventMessage,
  SubscribeToTriggerMessage,
  Command,
} from '@websocket-client';

export type {
  IHomeAssistant,
  GetHistoryParams,
  DeviceTarget,
  EntityTarget,
  GetLogbookParams,
  HassEntity,
  HassConfig,
  Context,
  CalendarDetails,
  EventDetails,
  ServiceField,
  ServiceFields,
  Config,
  HassDevice,
  Logger,
  State,
  LogBookEntry,
  ServiceDomainDetails,
  Service,
  Panel,
  HomeAssistantEvent,
  BaseEvent,
  UserAddedEvent,
  CallServiceEvent,
  UserRemovedEvent,
  LogbookEntryEvent,
  StateChangedEvent,
  HomeAssistantStopEvent,
  SceneReloadedEvent,
  ScriptStartedEvent,
  ThemesUpdatedEvent,
  ServiceRemovedEvent,
  ComponentLoadedEvent,
  CoreConfigUpdatedEvent,
  ServiceRegisteredEvent,
  AutomationReloadedEvent,
  DataFlowProgressedEvent,
  HomeAssistantCloseEvent,
  HomeAssistantStartEvent,
  AutomationTriggeredEvent,
  HomeAssistantStartedEvent,
  HomeAssistantFinalWriteEvent,
  HassArea,
  NumberSelector,
  TemplateSelector,
  TextSelector,
  TimeSelector,
  DeviceSelector,
  SelectSelector,
  BooleanSelector,
  ObjectSelector,
  EntitySelector,
} from '@types';
