// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/automations/:id': {
    params: {
      id: string;
    };
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page: '/' | '/automations/:id';
  };
  './app.tsx': {
    id: 'app';
    page: '/';
  };
  './routes/automation.tsx': {
    id: 'routes/automation';
    page: '/automations/:id';
  };
};
