---
name: Hass Blocks
description: Building blocks for Home Assistant
version: 1.0.0
slug: hass-blocks
homeassistant_api: true
init: false
ports:
  3001/tcp: 3001
map:
  - config:rw
environment:
  NODE_ENV: production
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
