export const tsConfig = `
{
  "$schema": "https://json.schemastore.org/tsconfig.json",
  "compilerOptions": {
    "resolveJsonModule": true,
    "noErrorTruncation": true,
    "moduleResolution": "nodenext",
    "module": "nodenext",
    "declaration": true,
    "emitDeclarationOnly": true,
    "importHelpers": true,
    "isolatedModules": true,
    "lib": ["ESNext", "ESNext.Array"],
    "allowImportingTsExtensions": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es2022",
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noImplicitReturns": true,
    "noPropertyAccessFromIndexSignature": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noUncheckedIndexedAccess": true,
    "exactOptionalPropertyTypes": true,
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
  },
  "include": ["**/*.ts", "./.blocks/index.ts"]
}`;
